# Generated by Django 4.2.4 on 2024-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
